@extends('layouts.site')

@section('content')
    <section class="content-page legal-page">
        <p class="eyebrow">Legal</p>
        <h1>Terms of Service</h1>
        <div class="legal-content">
            <section>
                <h2>Please Read These Terms and Conditions of Use Carefully Before Using This Website.</h2>
                <p>Welcome to our website. If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy and website disclaimer, govern NOT DONE PTY LTD's relationship with you in relation to your use of this website.</p>
                <p>By using this website, you signify your acceptance of these terms and conditions of use. For the purposes of these terms and conditions, "Us", "Our" and "We" refers to NOT DONE PTY LTD and "You" and "Your" refers to you, the client, visitor, website user or person using our website.</p>
            </section>
            <section><h2>Amendment of Terms</h2><p>We reserve the right to change, modify, add or remove portions of these terms at any time. Please check these terms regularly prior to using our website to ensure you are aware of any changes. We will endeavour to highlight any significant or substantive changes to you where possible. If you choose to use our website then we will regard that use as conclusive evidence of your agreement and acceptance that these terms govern your and NOT DONE PTY LTD's rights and obligations to each other.</p></section>
            <section><h2>Limitation of Liability</h2><p>It is an essential precondition to you using our website that you agree and accept that NOT DONE PTY LTD is not legally responsible for any loss or damage you might suffer related to your use of the website, whether from errors or from omissions in our documents or information, any goods or services we may offer or from any other use of the website. This includes your use or reliance on any third party content, links, comments or advertisements. Your use of, or reliance on, any information or materials on this website is entirely at your own risk, for which we shall not be liable.</p><p>It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific, personal requirements. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p></section>
            <section><h2>Competition and Consumer Act</h2><p>Our goods and services come with guarantees that cannot be excluded, modified or restricted under the Australian Consumer Law and are in addition to any manufacturer or supplier warranty.</p><p>For the purposes of Schedule 2 of the Australian Consumer Law, in particular Sections 51 to 53, 64 and 64A of Part 3-2, Division 1, Subdivision A of the Competition and Consumer Act 2010 (Cth), NOT DONE PTY LTD's liability for any breach of a term of this agreement is limited to: the supplying of the goods or services to you again; the replacement of the goods; or the payment of the cost of having the goods or services supplied to you again.</p><p>You must be over 18 years of age to use this website and to purchase any goods or services.</p></section>
            <section><h2>Delivery of Goods</h2><p>Physical goods may be delivered by Australia Post and/or other reputable courier companies. Deliveries are processed promptly upon receipt of full payment. Delivery may take between 2 and 14 days, depending on the delivery option. Damaged or lost orders should be resolved with Australia Post or the courier company directly and we are not responsible for goods that are damaged in transit or not received. Replacement of damaged or lost items is made at the discretion of NOT DONE PTY LTD.</p><p>Digital goods are delivered immediately. Please be aware there are inherent risks associated with downloading any software and digital goods. Should you have any technical problems downloading any of our goods, please contact us so we may try to assist you.</p></section>
            <section><h2>Returns and Refunds</h2><p>NOT DONE PTY LTD handles returns and processes refunds in accordance with the Australian Consumer Protection legislation.</p><p>Should you wish to return your order, please notify us within 14 days of purchase with a valid reason for return. If we are unable to resolve your complaint or further assist you, we will process a refund upon timely receipt of the goods purchased. Unopened goods will be refunded in full. Refunds will be processed promptly and payment made by the same method that you made payment. All refunds are made at the discretion of NOT DONE PTY LTD.</p></section>
            <section><h2>Links to Other Websites</h2><p>NOT DONE PTY LTD may from time to time provide on the website, links to other websites, advertisements and information on those websites for your convenience. This does not necessarily imply sponsorship, endorsement, or approval or arrangement between NOT DONE PTY LTD and the owners of those websites. NOT DONE PTY LTD takes no responsibility for any of the content found on the linked websites.</p><p>NOT DONE PTY LTD's website may contain information or advertisements provided by third parties for which NOT DONE PTY LTD accepts no responsibility whatsoever for any information or advice provided to you directly by third parties. We are making a recommendation only and are not providing any advice nor do we take any responsibility for any advice received in this regard.</p></section>
            <section><h2>Disclaimer</h2><p>To the fullest extent permitted by law, NOT DONE PTY LTD absolutely disclaims all warranties, expressed or implied, including, but not limited to, implied warranties of merchantability and fitness for any particular purpose. NOT DONE PTY LTD gives no warranty that the documents, goods or services will be free of errors, or that defects will be corrected, or that our website or server is free of viruses or any other harmful components.</p><p>Whilst we, at all times endeavour to have the most accurate, reliable and up-to-date information on our website, we do not warrant or make any representations regarding the use or the result of the use of any document, product, service, link or information on the website or as to the correctness, suitability, accuracy, reliability, or otherwise.</p><p>It is your sole responsibility and not the responsibility of NOT DONE PTY LTD to bear any and all costs of servicing, repairs, or correction. The applicable law in your state or territory may not permit these exclusions, particularly the exclusions of some implied warranties. Some of the above may not apply to you but you must ensure you are aware of any risk you may be taking by using this website or any products or services that may be offered through it. It is your responsibility to do so.</p></section>
            <section><h2>Your Privacy</h2><p>At NOT DONE PTY LTD, we are committed to protecting your privacy. We use the information we collect about you to maximise the services that we provide to you. We respect the privacy and confidentiality of the information provided by you and adhere to the Australian Privacy Principles. Please read our separate Privacy Policy carefully.</p><p>You may change your details at any time by advising us in writing via email. All information we receive from our customers is protected by our secure servers. Our secure server software encrypts all customer information before it is sent to us. Furthermore, all customer data collected is secured against unauthorised use or access. Credit card information is not stored by us on our servers.</p></section>
            <section><h2>Third Parties</h2><p>We do not and will not sell or deal in personal or customer information. We may however use in a general sense without any reference to your name, your information to create marketing statistics, identify user demands and assist in meeting customer needs generally. In addition, we may use the information that you provide to improve our website and services but not for any other use.</p></section>
            <section><h2>Disclosure of Information</h2><p>NOT DONE PTY LTD may be required, in certain circumstances, to disclose information in good faith and where NOT DONE PTY LTD is required to do so in the following circumstances: by law or by any court; to enforce the terms of any of our customer agreements; or to protect the rights, property or safety of our customers or third parties.</p></section>
            <section><h2>Exclusion of Competitors</h2><p>If you are in the business of creating similar documents, goods or services for the purpose of providing them for a fee to users, whether they be business users or domestic users, then you are a competitor of NOT DONE PTY LTD. NOT DONE PTY LTD expressly excludes and does not permit you to use or access our website, to download any documents or information from our website or obtain any such documents or information through a third party. If you breach this term then NOT DONE PTY LTD will hold you fully responsible for any loss that we may sustain and further hold you accountable for all profits that you might make from such unpermitted and improper use. NOT DONE PTY LTD reserves the right to exclude and deny any person access to our website, services or information in our sole discretion.</p></section>
            <section><h2>Copyright, Trademark and Restrictions of Use</h2><p>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance, trademarks and graphics. You are not permitted to reproduce the documents, information or materials on the website for the purposes of sale or the use by any third party. In particular you are not permitted to republish, upload, transmit electronically or otherwise or distribute any of the materials, documents or products that may be available for download from time to time on this website.</p><p>NOT DONE PTY LTD expressly reserves all copyright and trademark in all documents, information and materials on our website and we reserve the right to take action against you if you breach any of these terms.</p><p>Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following: you may print or download to a local hard disk extracts for your personal and non-commercial use only; and you may copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material.</p><p>You may not, except with our express written permission, distribute or commercially exploit the content. Nor may you transmit it or store it on any other website or other form of electronic retrieval system.</p></section>
            <section><h2>Whole Agreement</h2><p>These terms and conditions represent the whole agreement between you and NOT DONE PTY LTD concerning your use and access to our website and your use and access to the documents and information on it. No other term is to be included in this agreement except where it is required to be included by any legislation of the Commonwealth or any State or Territory. All implied terms except those implied by statute and which cannot be expressly excluded are hereby expressly excluded.</p></section>
            <section><h2>Exclusion of Unenforceable Terms</h2><p>Where any clause or term above would by any applicable statute be illegal, void, or unenforceable in any State or Territory then such a clause shall not apply in that State or Territory and shall be deemed never to have been included in these terms and conditions in that State or Territory. Such a clause if legal and enforceable in any other State or Territory shall continue to be fully enforceable and part of this agreement in those other States and Territories. The deemed exclusion of any term pursuant to this paragraph shall not affect or modify the full enforceability and construction of the other clauses of these terms and conditions.</p></section>
            <section><h2>Jurisdiction</h2><p>This agreement and this website are subject to the laws of WA and Australia. If there is a dispute between you and NOT DONE PTY LTD that results in litigation then you must submit to the jurisdiction of the courts of WA.</p></section>
        </div>
    </section>
@endsection
